[package]
name = "guessing-number-game"
version = "0.2.0"
edition = "2021"
authors = ["Waryen"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
colored = "2.0.0"
